### ISSUE TITLE
How to use nearest neighbor interpolation?

### ISSUE THREAD

**Issue by VanushVaswani** [actarian/vscode-glsl-canvas#37]
When sampling from a 64 x 64 texture (Bayer matrix), I get the below in the preview.

![image](https://user-images.githubusercontent.com/7519133/71567167-154c9400-2b11-11ea-895c-02bdc5d012c6.png)

However, I expected a matrix-like texture. Any idea how to switch to nearest neighbor?

**Comment by actarian** [comment]
@VanushVaswani  `glsl-canvas` supports `{ filtering: 'nearest' }` as texture option, but due to the way `vscode-glsl-canvas` plugin currently handle textures is not possible to pass parameters. I'm trying to add the feature with those two proposal:  

*proposal 1*  
adding texture options as evaluable object after texture url
```
uniform sampler2D u_texture; // data/bayer-matrix.png : { filtering: 'nearest' }
```

*proposal 2*  
adding texture options as querystring of the texture url
```
uniform sampler2D u_texture; // data/bayer-matrix.png?filtering=nearest
```

latter proposal could work with vscode glsl-canvas settings too:

```
{
    "glsl-canvas.textures": {
        "0": "./data/bayer-matrix.png?filtering=nearest",
    }
}
```

**Comment by VanushVaswani** [comment]
I like proposal 2!

**Comment by actarian** [comment]
@VanushVaswani proposal 2 has been added to latest plugin release! Thank You!

**Comment by willstall** [comment]
Is there a way to set wrap/repeat modes with this method as well?
